-- AlterTable
ALTER TABLE "Blog" ADD COLUMN     "excerpt" TEXT DEFAULT '',
ADD COLUMN     "publishedAt" TIMESTAMP(3),
ADD COLUMN     "version" INTEGER NOT NULL DEFAULT 1,
ALTER COLUMN "slug" DROP NOT NULL,
ALTER COLUMN "title" DROP NOT NULL,
ALTER COLUMN "title" SET DEFAULT '',
ALTER COLUMN "plainText" DROP NOT NULL,
ALTER COLUMN "plainText" SET DEFAULT '',
ALTER COLUMN "enrichedText" DROP NOT NULL,
ALTER COLUMN "htmlText" DROP NOT NULL,
ALTER COLUMN "htmlText" SET DEFAULT '';
