export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  INTERNAL_SERVER_ERROR: 500,
} as const;

export const USER_ROLES = {
  USER : 'USER',
  MODERATOR : 'MODERATOR',
  ADMIN : 'ADMIN'
} as const;

export const TOKEN_EXPIRY = {
  ACCESS_TOKEN : "15m",
  REFRESH_TOKEN : "7d",
  REFRESH_TOKEN_DAYS : 7
} as const;